version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: beyondnet
      MONGO_INITDB_ROOT_PASSWORD: beyondnet
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb_data:
